export const cuisineData = [
  { "id": 1, "Cuisine": "Indian" },
  { "id": 2, "Cuisine": "South Indian Recipes" },  
  { "id": 3, "Cuisine": "Andhra" },
  { "id": 4, "Cuisine": "Udupi" },
  { "id": 5, "Cuisine": "Mexican" },
  { "id": 6, "Cuisine": "Fusion" },
  { "id": 7, "Cuisine": "Continental" },
  { "id": 8, "Cuisine": "Bengali Recipes" },       
  { "id": 9, "Cuisine": "Punjabi" },
  { "id": 10, "Cuisine": "Chettinad" },
  { "id": 11, "Cuisine": "Tamil Nadu" },
  { "id": 12, "Cuisine": "Maharashtrian Recipes" },
  { "id": 13, "Cuisine": "North Indian Recipes" }, 
  { "id": 14, "Cuisine": "Italian Recipes" },      
  { "id": 15, "Cuisine": "Sindhi" },
  { "id": 16, "Cuisine": "Thai" },
  { "id": 17, "Cuisine": "Chinese" },
  { "id": 18, "Cuisine": "Kerala Recipes" },
  { "id": 19, "Cuisine": "Gujarati Recipes" },
  { "id": 20, "Cuisine": "Coorg" },
  { "id": 21, "Cuisine": "Rajasthani" },
  { "id": 22, "Cuisine": "Asian" },
  { "id": 23, "Cuisine": "Middle Eastern" },
  { "id": 24, "Cuisine": "Coastal Karnataka" },
  { "id": 25, "Cuisine": "European" },
  { "id": 26, "Cuisine": "Kashmiri" },
  { "id": 27, "Cuisine": "Karnataka" },
  { "id": 28, "Cuisine": "Lucknowi" },
  { "id": 29, "Cuisine": "Hyderabadi" },
  { "id": 30, "Cuisine": "Side Dish" },
  { "id": 31, "Cuisine": "Goan Recipes" },
  { "id": 32, "Cuisine": "Arab" },
  { "id": 33, "Cuisine": "Assamese" },
  { "id": 34, "Cuisine": "Bihari" },
  { "id": 35, "Cuisine": "Malabar" },
  { "id": 36, "Cuisine": "Himachal" },
  { "id": 37, "Cuisine": "Awadhi" },
  { "id": 38, "Cuisine": "Cantonese" },
  { "id": 39, "Cuisine": "North East India Recipes" },
  { "id": 40, "Cuisine": "Sichuan" },
  { "id": 41, "Cuisine": "Mughlai" },
  { "id": 42, "Cuisine": "Japanese" },
  { "id": 43, "Cuisine": "Mangalorean" },
  { "id": 44, "Cuisine": "Vietnamese" },
  { "id": 45, "Cuisine": "British" },
  { "id": 46, "Cuisine": "North Karnataka" },
  { "id": 47, "Cuisine": "Parsi Recipes" },
  { "id": 48, "Cuisine": "Greek" },
  { "id": 49, "Cuisine": "Nepalese" },
  { "id": 50, "Cuisine": "Oriya Recipes" },
  { "id": 51, "Cuisine": "French" },
  { "id": 52, "Cuisine": "Indo Chinese" },
  { "id": 53, "Cuisine": "Konkan" },
  { "id": 54, "Cuisine": "Mediterranean" },
  { "id": 55, "Cuisine": "Sri Lankan" },
  { "id": 56, "Cuisine": "Uttar Pradesh" },
  { "id": 57, "Cuisine": "Malvani" },
  { "id": 58, "Cuisine": "Indonesian" },
  { "id": 59, "Cuisine": "African" },
  { "id": 60, "Cuisine": "Shandong" },
  { "id": 61, "Cuisine": "Korean" },
  { "id": 62, "Cuisine": "American" },
  { "id": 63, "Cuisine": "Kongunadu" },
  { "id": 64, "Cuisine": "Caribbean" },
  { "id": 65, "Cuisine": "South Karnataka" },
  { "id": 66, "Cuisine": "Pakistani" },
  { "id": 67, "Cuisine": "Haryana" },
  { "id": 68, "Cuisine": "Appetizer" },
  { "id": 69, "Cuisine": "Uttarakhand-North Kumaon" },
  { "id": 70, "Cuisine": "World Breakfast" },
  { "id": 71, "Cuisine": "Malaysian" },
  { "id": 72, "Cuisine": "Dessert" },
  { "id": 73, "Cuisine": "Hunan" },
  { "id": 74, "Cuisine": "Dinner" },
  { "id": 75, "Cuisine": "Snack" },
  { "id": 76, "Cuisine": "Jewish" },
  { "id": 77, "Cuisine": "Burmese" },
  { "id": 78, "Cuisine": "Afghan" },
  { "id": 79, "Cuisine": "Brunch" },
  { "id": 80, "Cuisine": "Jharkhand" },
  { "id": 81, "Cuisine": "Lunch" },
  { "id": 82, "Cuisine": "Nagaland" }
];